# rustfmt configuration for 2024 (stable channel)
# See https://rust-lang.github.io/rustfmt/ for all options

# Basics
edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

# Code structure
reorder_imports = true
reorder_modules = true

# Spacing and alignment
use_small_heuristics = "Default"
fn_params_layout = "Tall"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
use_field_init_shorthand = true

# Advanced
merge_derives = true
use_try_shorthand = true